name: Move Markdown Files
on:
  push:
jobs:
  move-markdown-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Move .md Files to Drafts Folder
        run: |
          mkdir -p ubuntu/content/drafts
          find ubuntu/content -maxdepth 1 -name "*.md" ! -name "index.md" -exec mv {} ubuntu/content/drafts \;
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ubuntu/content/drafts
          git commit -m "Move .md files to drafts folder" || echo "No .md files to move."
          git push
        env:
          MY_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
