name: Sync Folder to Another Repository

on:
  push:
    branches:
      - v4  # Or your default branch

jobs:
  file-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'  # Specify Node.js version 20.x here

      - name: Sync Folder
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: .github/workflows/sync.yml
